- name: Deploy Node.js app to Kubernetes
  hosts: localhost
  tasks:
    - name: Deploy Kubernetes Deployment
      command: kubectl apply -f k8s/deployment.yml
      args:
        chdir: ..

    - name: Deploy Kubernetes Service
      command: kubectl apply -f k8s/service.yml
      args:
        chdir: ..

    - name: Update image with Jenkins build number
      command: kubectl set image deployment/devops-tp-node devops-tp-node=nourayari/devops-tp-node:{{ image_tag }}

    - name: Wait for deployment rollout
      command: kubectl rollout status deployment/devops-tp-node